# Generated by Django 3.0.7 on 2020-07-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('major', models.CharField(max_length=40)),
            ],
        ),
    ]
