# Generated by Django 3.0.7 on 2020-07-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
