# Generated by Django 3.0.3 on 2020-07-07 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('account', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('cities', models.CharField(max_length=40)),
                ('age', models.CharField(max_length=40)),
                ('qq', models.CharField(max_length=40)),
                ('sig', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=40)),
                ('head', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('photo_id', models.AutoField(max_length=100, primary_key=True, serialize=False)),
                ('age', models.CharField(max_length=3)),
                ('glasses', models.BooleanField()),
                ('public', models.BooleanField()),
                ('emotion', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('face_shape', models.CharField(max_length=20)),
                ('expression', models.CharField(max_length=20)),
                ('base64', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('beauty', models.FloatField()),
                ('face_width', models.CharField(max_length=20)),
                ('face_height', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=20)),
                ('share_info', models.CharField(max_length=300)),
                ('image_name', models.CharField(max_length=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fd', to='app.User')),
                ('follower_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fr', to='app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=300)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Photo')),
            ],
        ),
    ]
