# Generated by Django 3.0.3 on 2020-07-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comments_favorites_follow_photo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
