# Generated by Django 3.0.3 on 2020-07-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200707_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
